// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dowubmlzofjvqyokwqrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvd3VibWx6b2ZqdnF5b2t3cXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzkyMTksImV4cCI6MjA2NTcxNTIxOX0.3MzCfE1RVPyg97jZac7vK36Wl-nK1Cm-DDnbrcFOaW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);